export const WORK_ORDER = {
    GET_WORK_ORDER_SUCCESS : 'GET_WORK_ORDER_SUCCESS',
    GET_WORK_ORDER_FAILURE : 'GET_WORK_ORDER_FAILURE',
    GET_WORK_ORDER_OVERDUE_COUNT_SUCCESS : 'GET_WORK_ORDER_OVERDUE_COUNT_SUCCESS',
    GET_WORK_ORDER_OVERDUE_COUNT_FAILURE : 'GET_WORK_ORDER_OVERDUE_COUNT_FAILURE'
};